### ISSUE TITLE
[BUG] can't download the thing off pling

### ISSUE THREAD

**Issue by LunarSocks** [Silicasandwhich/Bibata_Cursor_Translucent#10]
**Describe the bug**
says "This XML file does not appear to have any style information associated with it. The document tree is shown below. when i try to download it off the website

**To Reproduce**
1. go to (https://www.pling.com/p/1437885/)
2. download
3. see error

**Expected behavior**
it downloads

**Additional context**
i really want this cursor, reuploading on pling would probably solve the issue but straight up just uploading it on github would be better too

**Comment by silica-dev** [comment]
hey there, I don't have time today to look into this issue, but in the meantime, you should be able to download it [here](https://github.com/Silicasandwhich/Bibata_Cursor_Translucent/releases/tag/v1.1.2). thanks for bringing this to my attention

**Comment by LunarSocks** [comment]
thanks my guy 😭 im still a lil bit inexperienced when it comes to linux and downloading stuff from github so THANK YOU
