### ISSUE TITLE
Help with installing in Windows 10

### ISSUE THREAD

**Issue by NinjaShuriken** [Silicasandwhich/Bibata_Cursor_Translucent#5]
First off I would like to say I really REALLY liked your translucent colors they look awesome on my Manjaro install, so I wanted them on Windows too but I cannot find the zip file for the Windows version of the cursors, and I have no idea on how to compile them into a Windows version with .cur/,ani file extensions, any help would be greatly appreciated. Thanks.

**Comment by silica-dev** [comment]
if you download [this release](https://github.com/Silicasandwhich/Bibata_Cursor_Translucent/releases/tag/v1.0.1-windows-2) and then go to src\Bibata_[your flavor]\Windows, you should see all the cursor files. Hope this helps!

**Comment by NinjaShuriken** [comment]
That is exactly what i was searching for, thanks a lot for your help.
