### ISSUE TITLE
One of the diagonal resize icons is missing

### ISSUE THREAD

**Issue by Nielicht** [Silicasandwhich/Bibata_Cursor_Translucent#8]
One of the diagonal resize icons is missing, specifically the one that appears when you resize a window from the bottom right corner, as can be seen in the attached images. 

This currently happens in both my Arch (installed through AUR) and Fedora 36 (installed through the shell script) machines, with all the translucent cursors.

![imagen](https://user-images.githubusercontent.com/51968429/194586470-2e5ef811-6ff4-4f2d-83fe-7a5d294a5051.png)
![imagen](https://user-images.githubusercontent.com/51968429/194586579-06963de6-b56d-46fa-bb16-ed4ae11d211a.png)
![imagen](https://user-images.githubusercontent.com/51968429/194586738-47adb961-a1cc-4523-8a36-48778cd26364.png)
![imagen](https://user-images.githubusercontent.com/51968429/194586789-9c1cce8a-0c2d-45bf-8394-ee19b3c92fac.png)

**Comment by silica-dev** [comment]
I've reproduced the bug on my machine. I will work on a fix today.

**Comment by silica-dev** [comment]
issue appears to be fixed, make sure to verify on your end by updating via aur or reinstalling

**Comment by Nielicht** [comment]
Yep, it's now fixed!
